# Generated by Django 3.2.7 on 2021-09-27 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Hoel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryCode', models.CharField(max_length=20)),
                ('CategoryName', models.CharField(max_length=50)),
                ('TotalRoom', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerCode', models.CharField(max_length=20)),
                ('FullName', models.CharField(max_length=100)),
                ('CustomerTel', models.CharField(max_length=12)),
                ('CCCD', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Room_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomCode', models.CharField(max_length=20)),
                ('KindOfRoom', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Status', models.CharField(max_length=100)),
                ('RoomTel', models.CharField(max_length=12)),
                ('CategoryCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category_hoel')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceCode', models.CharField(max_length=20)),
                ('ServiceName', models.CharField(max_length=50)),
                ('UnitPrice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room_Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer_info')),
                ('RoomCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.room_info')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceivedDate', models.DateField()),
                ('CustomerCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer_info')),
                ('RoomCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.room_info')),
            ],
        ),
    ]
